version: '3.2'

services:

# The Application
  php-apache:
    container_name: ${PHP_APACHE_NAME}
    build:
        context:  ./apache
        dockerfile: Dockerfile
    depends_on:
      - mongodb
    volumes:
        - ${APP_DATA_PATH}/${PROJECT_NAME}:/var/www/html/
    ports:
        - ${PHP_APACHE_PORT}:80

  #workspace
  workspace:
    build:
      context: ./workspace
    container_name: ${WORKSPACE_NAME}
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ${APP_DATA_PATH}:/var/www/

  # mongodb
  mongodb:
    build: ./mongodb
    container_name: ${MONGO_NAME}
    restart: always
    volumes:
      - ./mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ${MONGO_DATA_PATH}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORTS}:27017