FROM mongo:latest
WORKDIR /var/lib

# RUN mongosh -u dev -p Rabiloo@123 --authenticationDatabase admin\
#     use payment-form \
#     db.createUser({user: "dev", pwd: "Rabiloo@123", roles: [{role:"readWrite", db:"payment-form"}]})

EXPOSE 27017